@startuml
'https://plantuml.com/class-diagram

class AirConditioner {
update(Direction d)
update(Int
}

class Temperature {
notify()
}
'templateパターンでwarmとcoolが実装できるかも？

'意図がindoorUnitと少し違うことを明確にするためにあえて違う名前にしてみた
class OutdoorUnit {
+releaseAir(Catalyst catalyst)
+absorbAir(Catalyst catalyst)
+compress(Catalyst catalyst)
+decompress(Catalyst catalyst)
}

class IndoorUnit {
-AirFlowController blowerOrAbsorber
+blow(Catalyst catalyst)
+absorb(Catalyst catalyst))
}

IndoorUnit o-right- AirFlowController

interface AirFlowController {
void blow(Catalyst catalyst)
void absorb(Catalyst catalyst)
}

AirFlowController <|-- ConstantAirFlowController
'TODO: autoとかの実装を後ほどする

class ConstantAirFlowController {
-Volume volume
-Direction direction
+AirFlowController(Volume volume, Direction d)
+void blow(Catalyst catalyst)
+void absorb(Catalyst catalyst)
}

ConstantAirFlowController --> Direction
ConstantAirFlowController --> Volume

enum Direction {
}

enum Volume {
}

@enduml