@startuml
'https://plantuml.com/class-diagram

'基本的には冷房と暖房の２つしか選べない
'風向の指定しかできない
'温度センサー未実装

class OperationController {
+turnOn(ModeButton b, Volume v, Direction d)
+turnOnWithAutoDirection(ModeButton b, Volume v)
+turnOnWithAutoVolume(ModeButton b, Direction d)
+turnOnWithAutoAirflow(ModeButton b)
+turnOnAutoMode()
+turnOff()
}

OperationController -right-> OperationMode

abstract class OperationMode {
-OutdoorUnit outdoorUnit
+operate()
}

OperationMode <|-- Cooler
OperationMode <|-- Heater
OperationMode <|-- Auto

OperationMode -right- OutdoorUnit

class Cooler {
-IndoorUnit indoorUnit
operate()
}

Cooler o-- IndoorUnit

class Heater {
-IndoorUnit indoorUnit
operate()
}

Heater o-- IndoorUnit

class Auto {
-IndoorUnit indoorUnit
operate()
}

Auto o-- IndoorUnit


'意図がindoorUnitと少し違うことを明確にするためにあえて違う名前にしてみた
class OutdoorUnit {
+releaseAir(Catalyst catalyst)
+absorbAir(Catalyst catalyst)
+compress(Catalyst catalyst)
+decompress(Catalyst catalyst)
}

class IndoorUnit {
-AirFlowController airFlowController
+blow(Catalyst catalyst)
+absorb(Catalyst catalyst)
}

IndoorUnit o-right- AirFlowController

interface AirFlowController {
void blow(Catalyst catalyst)
void absorb(Catalyst catalyst)
}

AirFlowController <|-- ConstantAirFlowController
AirFlowController <|-- AutoAirFlowController
AirFlowController <|-- AutoDirectionController
AirFlowController <|-- AutoVolumeController

class ConstantAirFlowController {
-Volume volume
-Direction direction
+void blow(Catalyst catalyst)
+void absorb(Catalyst catalyst)
}

class AutoAirFlowController {
+void blow(Catalyst catalyst)
+void absorb(Catalyst catalyst)
}

class AutoDirectionController {
+void blow(Catalyst catalyst)
+void absorb(Catalyst catalyst)
}

class AutoVolumeController {
+void blow(Catalyst catalyst)
+void absorb(Catalyst catalyst)
}

ConstantAirFlowController --> Direction
ConstantAirFlowController --> Volume
AutoVolumeController --> Direction
AutoDirectionController --> Volume

enum Direction {
}

enum Volume {
}

@enduml