@startuml

abstract class Ticket {
}

Ticket <|-- PriceTicket: implements
Ticket <|-- RideTicket: implements

class PriceTicket {
startPlace
price
}

class RideTicket {
startPlace
endPlace
}

Interface ElectricMoney {
}

ElectricMoney <|-- SuicaAdapter: implements
ElectricMoney <|-- PasmoAdapter: implements

class SuicaAdapter {
}
SuicaAdapter o-- Suica

class Suica {
}

class PasmoAdapter {
}

PasmoAdapter o-- Pasmo

class Pasmo {
}

@enduml