@startuml

class TrainGate {
+work()
-readByTicket()
-readByIC()
-open()
-close()
}

TrainGate *-right- ICReader
TrainGate *-left- TicketReader
TrainGate *-- Gate

class TicketReader {
}

TicketReader o-- Ticket

abstract class Ticket {
}

Ticket <|-- PriceTicket: imp
Ticket <|-- RideTicket: imp

class PriceTicket {
startPlace
price
}

class RideTicket {
startPlace
endPlace
}

Interface ElectricMoney {
}

ElectricMoney <|-- SuicaAdapter: imp
ElectricMoney <|-- PasmoAdapter: imp

class SuicaAdapter {
}
SuicaAdapter o-- Suica

class Suica {
}

class PasmoAdapter {
}

PasmoAdapter o-- Pasmo

class Pasmo {
}

class ICReader {

}

ICReader o-- ElectricMoney

class Gate {
close()
open()
}

@enduml